// Active runtime, report and provenance browser QA. Fixtures are explicitly
// authored test data in the dedicated PostgreSQL database, not provider output.
const { chromium } = require('../.ui-qa/node_modules/playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const { execFileSync } = require('node:child_process');
const root = path.join(__dirname, '..');
const out = path.join(root, 'frontend-ui-evidence');
const account = JSON.parse(fs.readFileSync(path.join(root, '.ui-qa/account.json')));
const ids = JSON.parse(fs.readFileSync(path.join(root, '.ui-qa/fixtures.json')));
const result = { fixtureNotice: 'Authored UI QA fixtures; not provider-generated analysis or live semantic verification', checks: [], screenshots: [], pageErrors: [] };
let browser, context, page;
const record = name => { result.checks.push(name); console.log(name, 'PASS'); };
const capture = async (name, width = 1440, height = 900) => {
  await page.setViewportSize({ width, height }); await page.waitForTimeout(300);
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
  const file = `${name}-${width}.png`; await page.screenshot({ path: path.join(out, file), fullPage: false });
  result.screenshots.push({ file, width, height, horizontalOverflow: overflow }); assert.equal(overflow, false, file);
};
async function main() {
  browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
  context = await browser.newContext({ ignoreHTTPSErrors: true, viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce' });
  page = await context.newPage(); page.on('pageerror', error => result.pageErrors.push(error.message));
  await page.goto('https://localhost:13000'); await page.getByLabel('Email', { exact: true }).fill(account.email); await page.getByLabel('Password', { exact: true }).fill(account.password);
  const authWait = page.waitForResponse(response => response.url().endsWith('/auth/login'));
  await page.getByRole('button', { name: 'Sign in', exact: true }).click(); const auth = (await (await authWait).json()).data;
  await page.getByRole('heading', { name: 'Your workspaces' }).waitFor(); await capture('dashboard-with-sources');
  const streams = [];
  page.on('request', request => { if (request.url().endsWith('/stream')) streams.push({ cursor: request.headers()['last-event-id'], bearer: Boolean(request.headers().authorization), queryToken: /[?&]token=/.test(request.url()) }); });
  await page.goto(`https://localhost:13000/workspaces/${ids.workspaceId}?investigation=${ids.activeId}`);
  await page.getByText('Live connection', { exact: true }).waitFor();
  await page.getByText('Tool started', { exact: true }).waitFor();
  await capture('active-investigation');
  await page.setViewportSize({ width: 1280, height: 800 }); await page.getByRole('button', { name: /^Trace/ }).click(); await capture('active-trace', 1280, 800);
  await capture('active-trace', 390, 844);
  const before = await page.getByRole('heading', { name: 'Lifecycle events' }).locator('..').innerText();
  await context.setOffline(true);
  await context.request.post('https://localhost:13000/__uiqa/disconnect-streams');
  await page.getByText('Offline · retrying', { exact: true }).waitFor(); await capture('offline-trace', 390, 844);
  execFileSync('python', ['scripts/ui_qa_seed.py', '--append'], { cwd: root, stdio: 'pipe' });
  await context.setOffline(false); await page.getByText('Live connection', { exact: true }).waitFor({ timeout: 20000 }); await page.getByText('Tool completed', { exact: true }).waitFor();
  assert.ok(streams.length >= 2); assert.ok(streams.some(stream => stream.cursor)); assert.ok(streams.every(stream => stream.bearer && !stream.queryToken));
  assert.equal(await page.getByText('Tool started', { exact: true }).count(), 1);
  assert.notEqual(await page.getByRole('heading', { name: 'Lifecycle events' }).locator('..').innerText(), before);
  record('Actual persisted SSE / offline recovery / Last-Event-ID / event dedupe');
  await page.getByRole('button', { name: 'Cancel', exact: true }).click(); await page.getByText('Investigation cancelled.', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Investigation', exact: true }).click(); await page.getByRole('heading', { name: 'Investigation cancelled', exact: true }).waitFor();
  await capture('cancelled-investigation', 390, 844); record('Actual cancellation preserves trace');
  await page.goto(`https://localhost:13000/workspaces/${ids.workspaceId}?investigation=${ids.reportId}`);
  await page.getByRole('heading', { name: 'Executive summary', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Copy report', exact: true }).click(); await page.getByRole('button', { name: 'Copied', exact: true }).waitFor(); record('Report clipboard feedback');
  await capture('report-fixture', 390, 844); await capture('report-fixture', 768, 900); await capture('report-fixture', 1280, 800); await capture('report-fixture', 1440, 900);
  await page.evaluate(() => document.documentElement.style.zoom = '2');
  await capture('report-fixture-css-zoom-200', 1440, 900);
  await page.evaluate(() => document.documentElement.style.zoom = '');
  record('200% CSS zoom report overflow check (browser zoom not simulated)');
  await page.getByRole('heading', { name: 'Claims', exact: true }).scrollIntoViewIfNeeded(); await capture('claims-fixture');
  assert.equal(await page.getByText('Verification not reported', { exact: true }).count(), 1);
  assert.equal(await page.getByText('References verified', { exact: true }).count(), 2);
  assert.equal(await page.getByText('Provider-reported confidence:', { exact: false }).count(), 0);
  await page.getByRole('button', { name: /^UI QA fixture: 24 requests/ }).click();
  await page.getByRole('dialog', { name: 'Evidence and provenance' }).waitFor(); await page.getByText('Formula / code', { exact: true }).click();
  await capture('calculation-lineage-fixture'); await capture('calculation-lineage-fixture', 390, 844);
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: `Inspect citation ${ids.evidenceId}`, exact: true }).first().click();
  const drawer = page.getByRole('dialog', { name: 'Evidence and provenance' }); await drawer.waitFor();
  await capture('evidence-lineage-fixture', 390, 844); await capture('evidence-lineage-fixture', 1440, 900);
  await drawer.getByRole('button', { name: 'Inspect source', exact: true }).click();
  await page.getByRole('dialog', { name: 'operating-review-qa.txt' }).waitFor(); await page.getByText('INTERFACE QA TEST DATA ONLY.', { exact: false }).first().waitFor();
  await page.keyboard.press('Escape'); assert.ok(page.url().includes(ids.reportId)); record('Report / unknown verification / null confidence / citation / source context');
  await page.getByRole('heading', { name: 'Recommendations', exact: true }).scrollIntoViewIfNeeded(); await capture('recommendations-fixture'); await capture('recommendations-fixture', 390, 844);
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.getByRole('button', { name: 'quarterly_costs_qa', exact: false }).first().click();
  await page.getByRole('heading', { name: 'Column profile' }).waitFor(); await capture('table-preview'); await capture('table-preview', 390, 844); await page.keyboard.press('Escape'); record('Actual extracted table preview');
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.getByRole('button', { name: 'Remove quarterly-costs-qa.csv', exact: true }).click();
  const removeDialog = page.getByRole('dialog', { name: 'Remove source?', exact: true });
  await removeDialog.getByRole('button', { name: 'Keep source', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'Remove quarterly-costs-qa.csv', exact: true }).count(), 1);
  record('Destructive source action confirmation / safe cancellation');
  // Revoke the real session through the public auth endpoint; the next read
  // must leave the protected view cleanly, without changing auth semantics.
  await context.request.post('https://localhost:13000/api/v1/auth/logout', { headers: { Authorization: `Bearer ${auth.token.access_token}`, Origin: 'https://localhost:13000' } });
  await page.reload(); await page.getByRole('heading', { name: 'Welcome back' }).waitFor();
  await page.getByText('Your session has ended. Sign in to continue.', { exact: true }).waitFor(); await capture('expired-session', 390, 844); record('Revoked session clean sign-in transition');
  assert.equal(result.pageErrors.length, 0); record('Runtime / report browser pass');
}
main().catch(async error => { result.failure = error.message; if (page) await page.screenshot({ path: path.join(out, 'runtime-failure.png') }).catch(() => {}); console.error(error.message); process.exitCode = 1; }).finally(async () => { fs.writeFileSync(path.join(out, 'runtime-browser-results.json'), JSON.stringify(result, null, 2)); await browser?.close(); });
